# Generated by Django 4.1.5 on 2023-01-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='articles',
            new_name='scopes',
        ),
    ]
